description: Allow all DS cartridges to boot in TWL

patches:
    patch1.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x08033164
            n3ds:
                0x00: 0x080331A0

    patch2.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x08033552
            n3ds:
                0x00: 0x0803358E

    patch3.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x0803355E
            n3ds:
                0x00: 0x0803359A

    patch4.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x0803356A
            n3ds:
                0x00: 0x080335A6
